import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const appSource = readFileSync(new URL("../static/app.js", import.meta.url), "utf8");
const cssSource = readFileSync(new URL("../static/app.css", import.meta.url), "utf8");
const indexSource = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const bubbleToolbarSource = appSource.slice(appSource.indexOf("function FeishuBubbleToolbar"), appSource.indexOf("function FeishuInsertMenu"));
const tableControlsSource = appSource.slice(appSource.indexOf("function FeishuTableControls"), appSource.indexOf("function TableInsertGrid"));

assert.match(appSource, /import \{ sortTableRows \} from "\.\/table-model\.mjs";/, "the editor should use the tested table sorting model");
assert.match(appSource, /Table\.configure\(\{ resizable: true, cellMinWidth: 96, lastColumnResizable: false \}\)/, "table columns should retain Tiptap's colgroup structure while custom dragging controls width changes");
assert.match(appSource, /const StyledTableCell = TableCell\.extend/, "table cells should persist formatting attributes");
assert.match(appSource, /backgroundColor/, "table cells should support persistent background colors");
assert.match(appSource, /textAlign/, "table cells should support persistent alignment");
assert.match(cssSource, /\.tableWrapper\s*\{[^}]*overflow-x: auto/, "wide inserted tables should scroll inside their own wrapper instead of overflowing the document");
assert.match(cssSource, /\.feishu-editor \.tableWrapper table\s*\{[^}]*max-width: none/, "wide inserted tables should be allowed to exceed the wrapper only within its scroll area");
assert.match(cssSource, /\.feishu-editor td:last-child \.column-resize-handle[\s\S]*display: none/, "the outer right table edge should not expose a resize rail");
assert.match(cssSource, /\.feishu-editor \.column-resize-handle\s*\{[\s\S]*display: none/, "native resize handles should stay hidden so only the fixed-width custom handles are draggable");
assert.match(cssSource, /\.feishu-editor \.column-resize-handle\s*\{[\s\S]*width: 6px/, "column borders should expose a forgiving resize target");
assert.match(cssSource, /\.feishu-editor td:hover \.column-resize-handle[\s\S]*background: #3370ff/, "hovering a column border should highlight the draggable line");
assert.match(cssSource, /\.feishu-editor\.resize-cursor\s*\{[\s\S]*cursor: col-resize/, "dragging a column border should show a horizontal resize cursor");
assert.match(appSource, /function persistTableColumnWidth\(/, "column dragging should persist explicit widths for the selected column");
assert.match(tableControlsSource, /table-column-drag-handle/, "only internal table borders should expose custom drag handles");
assert.match(tableControlsSource, /const nextWidth = Math\.max\(96, state\.rightWidth - delta\);/, "dragging a border should shrink the adjacent column instead of moving later borders");
assert.match(appSource, /function FeishuTableControls/, "the editor should render controls for the active table");
assert.match(appSource, /function TableInsertGrid/, "table insertion should support selecting a grid size");
assert.match(appSource, /merge-or-split/, "the table toolbar should merge and split selected cells");
assert.match(appSource, /sort-ascending/, "the table toolbar should sort the active column");
assert.match(indexSource, /app\.js\?v=20260723-math-v1/, "the page should request the updated table editor module instead of a cached script");
assert.match(bubbleToolbarSource, /tableSelectionInfo\(editor\)/, "the normal text toolbar should stay hidden for table selections");
assert.match(bubbleToolbarSource, /\{ label: "H3", command: "h3"/, "the selected-text toolbar should expose a level-three heading button");
assert.match(bubbleToolbarSource, /command: "textColor"/, "the selected-text toolbar should expose a text color palette trigger");
assert.doesNotMatch(bubbleToolbarSource, /command: "highlight"/, "the selected-text toolbar should not expose a separate highlight button");
assert.doesNotMatch(bubbleToolbarSource, /highlight-icon/, "the selected-text toolbar should not keep separate highlight icon styling");
assert.match(bubbleToolbarSource, /\{ label: "A", command: "textColor"/, "the selected-text toolbar should keep A for text color");
assert.match(bubbleToolbarSource, /backgroundColors/, "the color panel should keep background highlight choices");
assert.match(bubbleToolbarSource, /feishu-color-panel/, "the selected-text toolbar should render a compact color panel");
assert.match(appSource, /import Color from "https:\/\/esm\.sh\/@tiptap\/extension-color@2\.11\.7";/, "text color should use Tiptap color extension");
assert.match(appSource, /import katex from "https:\/\/esm\.sh\/katex@0\.16\.22";/, "math rendering should use KaTeX in the browser");
assert.match(appSource, /const MathInline = Node\.create/, "the editor should support inline math nodes");
assert.match(appSource, /const MathBlock = Node\.create/, "the editor should support block math nodes");
assert.match(appSource, /markdownTextToHtmlWithMath/, "pasted Markdown formulas should be converted before insertion");
assert.match(appSource, /function insertBlockWithEditableParagraph/, "block atoms should add a real editable paragraph after insertion");
assert.match(appSource, /function maybeReplaceGapCursorWithParagraph/, "pressing Enter on a gap cursor should create a normal paragraph");
assert.match(appSource, /selection\.constructor\?\.name === "GapCursor"/, "the gap cursor fallback should target ProseMirror gap cursors");
assert.match(appSource, /insertBlockWithEditableParagraph\(editor, \{[\s\S]*type: "image"/, "inserted images should leave the cursor in a following paragraph");
assert.match(appSource, /if \(empty\) \{[\s\S]*insertBlockWithEditableParagraph\(editor, node\)/, "inserted block formulas should leave the cursor in a following paragraph");
assert.match(indexSource, /katex@0\.16\.22\/dist\/katex\.min\.css/, "KaTeX styles should be loaded for rendered formulas");
assert.match(appSource, /import TextStyle from "https:\/\/esm\.sh\/@tiptap\/extension-text-style@2\.11\.7";/, "text color should be stored through Tiptap textStyle marks");
assert.match(appSource, /if \(command === "text-color-reset"\) return chain\.unsetColor/, "editor commands should reset selected text color before matching color prefixes");
assert.match(appSource, /if \(command\.startsWith\("text-color-"\)\) return chain\.setColor/, "editor commands should apply selected text colors");
assert.match(appSource, /const lineThreshold = 8;/, "row and column controls should only activate near table grid lines");
assert.match(appSource, /editor\.view\.dom\.addEventListener\("mousemove"/, "table controls should follow pointer movement over grid lines");
assert.match(tableControlsSource, /table-top-rail/, "hovering a table should render the gray table rails");
assert.match(tableControlsSource, /table-column-selector/, "column actions should be available only from the top edge");
assert.match(tableControlsSource, /table-row-selector/, "row actions should be available only from the left edge");
assert.match(tableControlsSource, /table-selection-toolbar/, "selected rows and columns should use one compact table toolbar");
assert.doesNotMatch(tableControlsSource, /table-cell-toolbar/, "table controls should not float beside an individual cell");
assert.match(tableControlsSource, /table-top-rail/, "hovering a table should reveal a gray column-selection rail above it");
assert.match(tableControlsSource, /table-left-rail/, "hovering a table should reveal a gray row-selection rail beside it");
assert.doesNotMatch(tableControlsSource, /table-rail-plus/, "rail dots should insert directly without an extra hover button");
assert.match(tableControlsSource, /const hasTableTextSelection = Boolean\(tableInfo && !editor\.state\.selection\.empty && !nativeLineKind\);/, "table text selections should retain their table-specific toolbar");
assert.match(tableControlsSource, /table-rail-dot/, "each gray rail segment should expose a small insert trigger point");
assert.match(tableControlsSource, /const toolbarAnchorRect =/, "the table toolbar should anchor near the selected text or line");
assert.match(tableControlsSource, /if \(!nextTableInfo \|\| !tableSelectionKind\(editor\)\) setSelectedLine\(null\);/, "table line selection should clear after leaving the table or changing to text selection");
assert.doesNotMatch(tableControlsSource, /table-hover-line/, "actual grid lines should not trigger table editing controls");
assert.match(tableControlsSource, /const railHoverPadding = 32;/, "the table hover area should include the surrounding rails");
assert.match(tableControlsSource, /shell\.addEventListener\("mousemove"/, "the rail-aware hover boundary should be tracked from the whole table shell");
assert.match(cssSource, /\.table-top-rail \.table-rail-dot\s*\{[\s\S]*left: 100%/, "top rail dots should align with each column's right grid line");
assert.match(cssSource, /\.table-left-rail \.table-rail-dot\s*\{[\s\S]*top: 100%/, "left rail dots should align with each row's bottom grid line");
assert.match(appSource, /table-rail-dot column/, "column insert dots should expose a column-specific hover state");
assert.match(appSource, /table-rail-dot row/, "row insert dots should expose a row-specific hover state");
assert.match(cssSource, /content: "插入列"/, "column insert dots should explain their action on hover");
assert.match(cssSource, /content: "插入行"/, "row insert dots should explain their action on hover");
assert.doesNotMatch(cssSource, /\.table-column-selector:hover \.table-rail-dot::after[\s\S]*content: "\+"/, "hovered rail dots should not display a plus sign");
assert.match(cssSource, /top: -14px/, "column insert prompts should stay close to their dots");
assert.match(cssSource, /right: 5px/, "row insert prompts should stay close to their dots");
assert.match(appSource, /function highlightTableLine\(/, "selecting a rail should immediately highlight the matching table line");
assert.match(tableControlsSource, /onPointerDown: \(event\) => \{[\s\S]*selectLine\("column"/, "column rails should select on pointer down before the overlay can dismiss");
assert.match(tableControlsSource, /onPointerDown: \(event\) => \{[\s\S]*selectLine\("row"/, "row rails should select on pointer down before the overlay can dismiss");
assert.match(appSource, /function tableCellPosition\(/, "rail selection should resolve table cell node positions instead of depending on text cursor state");
assert.match(appSource, /function tableColumnTargets\(/, "column rails should be derived from visible table boundaries, including wide or merged cells");
assert.match(appSource, /editor\.commands\.setCellSelection\(\{ anchor, head \}\)/, "rail selection should create a native range from the first to last row or column cell");
assert.match(appSource, /editor\.commands\.selectRow\(\)|editor\.commands\.selectColumn\(\)/, "single-cell rows or columns should fall back to native line selection when a range cannot be created");
assert.match(tableControlsSource, /const columnTargets = tableColumnTargets\(table\);/, "top rail should render every visible column target");
assert.match(tableControlsSource, /const railViewportRect = table\.closest\("\.tableWrapper"\)\?\.getBoundingClientRect\(\) \|\| tableRect;/, "wide-table rails should be constrained to the visible scroll viewport");
assert.doesNotMatch(appSource, /prosemirror-tables@/, "table selection must not add a separate CDN module that can prevent the editor from booting");
assert.match(appSource, /function tableSelectionKind\(/, "native table selection should identify whether a whole row or column is selected");
assert.match(bubbleToolbarSource, /tableSelectionInfo\(editor\)/, "the regular document toolbar should stay hidden for every table selection");
assert.match(appSource, /event\.key === "Backspace" \|\| event\.key === "Delete"/, "Delete and Backspace should handle a selected table line");
assert.match(appSource, /delete-row" : "delete-column/, "keyboard deletion should remove the selected row or column");
assert.match(appSource, /if \(command === "delete-row" && tableInfo\?\.table\.childCount === 1\) return chain\.deleteTable\(\)\.run\(\);/, "deleting the only remaining row should remove the empty table");
assert.match(tableControlsSource, /const activeLine =/, "the table toolbar should derive actions from the live native selection");
assert.match(tableControlsSource, /const \[toolbarMenu, setToolbarMenu\] = useState\(null\);/, "table formatting controls should manage their own compact menus");
assert.match(tableControlsSource, /table-toolbar-popover/, "table toolbar dropdowns should be rendered beside the compact toolbar");
assert.match(tableControlsSource, /onPointerDown: \(event\) => activate\(event, command/, "toolbar commands should execute on pointer down without losing the table selection");
assert.match(tableControlsSource, /onPointerDown: \(event\) => openToolbarMenu\(event, "style"\)/, "text style options should open on click");
assert.match(tableControlsSource, /onPointerDown: \(event\) => openToolbarMenu\(event, "align"\)/, "alignment options should open on click");
assert.doesNotMatch(tableControlsSource, /table-structure-menu/, "the compact toolbar should not add a separate table structure button");
assert.match(tableControlsSource, /title: activeLine\.kind === "row" \? "删除行" : "删除列"/, "the full-line toolbar should include a direct delete control");
assert.match(appSource, /if \(command === "strike"\) return chain\.toggleStrike\(\)\.run\(\);/, "table toolbars should support strikethrough formatting");
assert.match(appSource, /if \(command\.startsWith\("highlight-"\)\)/, "table toolbars should support highlight color choices");
assert.match(appSource, /if \(command\.startsWith\("vertical-align-"\)\)/, "table toolbars should support vertical cell alignment");
assert.doesNotMatch(tableControlsSource, /sort-ascending|sort-descending/, "the compact toolbar should not include unrequested sorting controls");
assert.match(cssSource, /\.table-selection-toolbar\s*\{[\s\S]*pointer-events: auto/, "the table toolbar must opt back into pointer events inside the non-interactive overlay");
assert.match(cssSource, /\.table-toolbar-popover\s*\{[\s\S]*pointer-events: auto/, "table toolbar dropdowns must remain clickable inside the overlay");
assert.match(cssSource, /\.table-selection-toolbar\s*\{[^}]*overflow: visible/, "the main toolbar should not become a horizontal scrolling container");
assert.doesNotMatch(cssSource, /\.table-selection-toolbar\s*\{[^}]*overflow-x: auto/, "toolbar menus should render as independent floating panels, not in a scrollable toolbar");
assert.match(tableControlsSource, /const left = event\.currentTarget\.offsetLeft;/, "menu trigger geometry must be read before the React event is released");
assert.match(tableControlsSource, /\{ type, left \}/, "the deferred menu state update should use the captured trigger position");
assert.match(cssSource, /\.table-toolbar-popover button\s*\{[^}]*display: flex[^}]*align-items: center/, "menu icons and labels should stay on one line");
