import assert from "node:assert/strict";
import { normalizeSources, sourceURL, saveSource, moveSource, visibleSources } from "../static/sources-model.mjs";
import { buildPublishChangeSet, buildPublishChangeDetails, mergeSelectedPublishState, revertDraftChange } from "../static/publish-model.mjs";
import { validateBackup, mergeBackup } from "../static/knowledge-model.mjs";
import { notebookStateForPersistence, navigatePrimaryView, resolveStartupState } from "../static/library-ui-model.mjs";

const initial = normalizeSources();
assert.equal(initial.length, 6);
assert.deepEqual(normalizeSources([]), [], "Deleting every source must survive reinitialization");
for (const url of ["javascript:alert(1)", "data:text/html,test", "https://user:secret@example.org", "not a url"]) assert.equal(sourceURL(url), "");
assert.throws(() => saveSource(initial, { id: "bad", name: "重复", url: "https://hex2077.dev/#news" }), /已在清单/);
assert.equal(normalizeSources([...initial, initial[0]]).length, 6);
const changed = saveSource(initial, { id: "new", name: "新网站", url: "https://example.org", description: "研究阅读", category: "日报", pinned: true });
assert.equal(visibleSources(changed)[0].id, "new");
assert.equal(visibleSources(changed, "研究", "日报").length, 1);
assert.equal(moveSource(initial, initial[0].id, initial[2].id)[2].id, initial[0].id);
assert.equal(initial[0].id, "bestblogs", "Sorting must not mutate saved state");
const remote = { notes: [], folders: [], sources: initial };
const local = { ...remote, sources: changed, sourcesDirty: true, view: "sources" };
const changeSet = buildPublishChangeSet(local, remote);
assert.deepEqual(changeSet.selectedIds, ["sources"]);
assert.match(buildPublishChangeDetails(local, remote, changeSet.changes[0])[0].local, /新网站/);
assert.deepEqual(mergeSelectedPublishState(local, remote, new Set(["sources"])).state.sources, changed);
assert.deepEqual(mergeSelectedPublishState(local, remote, new Set()).state.sources, initial, "Other publications must retain remote sources");
assert.deepEqual(mergeSelectedPublishState({ ...local, sources: [] }, remote, new Set(["sources"])).state.sources, []);
assert.equal(revertDraftChange(local, remote, changeSet.changes[0]).sourcesDirty, false);
const persisted = JSON.parse(JSON.stringify(notebookStateForPersistence(local)));
assert.deepEqual(persisted.sources, changed);
assert.equal(persisted.sourcesDirty, true);
assert.equal(navigatePrimaryView(local, "sources").view, "sources");
assert.equal(resolveStartupState(local).view, "sources");
const backup = validateBackup({ version: 1, notes: [], folders: [], sources: changed });
assert.deepEqual(mergeBackup(remote, backup).sources, changed);
assert.deepEqual(mergeBackup(remote, { version: 1, notes: [], folders: [] }).sources, initial, "Legacy backups must not remove sources");
assert.deepEqual(mergeBackup(local, validateBackup({ version: 1, notes: [], folders: [], sources: [] })).sources, []);
assert.throws(() => validateBackup({ version: 1, notes: [], folders: [], sources: [{ id: "x", name: "x", url: "javascript:alert(1)" }] }), /信息源/);
console.log("Information sources: URL safety, deduplication, sorting, persistence, publish selection and backup tests passed");
